module.exports = {
    validateSuperAdmin: require("./SuperAdmin/createSuperAdmin"),
    validateLoginSuperAdmin: require("./SuperAdmin/loginSuperAdmin"),
    validateForgotPassword: require("./forgotPassword"),
    validateEditSuperAdmin: require("./SuperAdmin/editSuperAdmin"),
    validateUpdatePassword: require("./updatePassword"),
    validateCreateStaff: require("./Staff/createStaff"),
    validateLoginStaff: require("./Staff/loginStaff"),
    validateUpdateStaff: require("./Staff/updateStaff"),
    validatecreateAnnouncement: require("./Announcement/create"),
    validateUpdateAnnouncement: require("./Announcement/update"),
    validateCreateClass: require("./class/create"),
    validateCreateArm: require("./class/createArm"),
    validateUpdateClass: require("./class/update"),
    validateUpdateArm: require("./class/updateArm"),
    validateCreateSubject: require("./Subject/createSubject"),
    validateCreateSpecificSubject: require("./Subject/createSpecificSubject"),
    validateEditSubject: require("./Subject/editSubject"),
    validateCreateTimetable: require("./Timetable/create"),
    validateUpdateTimetable: require("./Timetable/update"),
    validateSetPeriodTime: require("./Timetable/setPeriodTime"),
    validateCreateSession : require('./session/create'),
    validateUpdateSession : require('./session/updateSession'),
    validateRegister: require("./student/register"),
    validateLinkParent: require("./student/linkParent"),
    validateEditStudent: require("./student/editStudent"),
    validateCreateParent: require("./parent/create"),
    validateEditParent: require("./parent/edit"),
    validateLinkStudent: require("./parent/linkStudent"),
    validateVerifyOTP: require("./verifyOTP"),
    validateResetPassword: require("./resetPassword"),
    validateCreateStaffAttendance: require("./Staff/createAttendance"),
    validateUpdateStaffAttendance: require("./Staff/updateAttendance"),
    validateCreateStudentAttendance: require("./student/createAttendance"),
    validateEditTerm: require("./session/editTerm.js"),
    validateCreateFee: require("./fee/create.js"),
    validateEditSpecificSubject: require("./Subject/editSpecificSubject.js"),
    validateCreateGradeSystem: require("./Grade/create.js"),
    validateUpdateGradeSystem: require("./Grade/update.js"),
    validateCreateAsssessmentFormat: require("./Assessment/create.js")
};
